name: generate monkeytype readme svg

on:
    schedule:
        - cron: "0 */24 * * *" # every 6 hours
    workflow_dispatch:

jobs:
    download-svg:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"

            - name: Generate Monkeytype Readme SVG
              uses: ridemountainpig/monkeytype-readme@v1.0.0
              with:
                  username: psypsyduck
                  themes: comfy
                  target-branch: monkeytype-readme
                  github-token: ${{ secrets.GITHUB_TOKEN }}
